import {state} from "./state.js";
export const $=id=>document.getElementById(id);export const key=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`};
export const fmtDate=k=>new Date(k+"T00:00:00").toLocaleDateString("ru-RU",{day:"numeric",month:"long"});
export const fmtTime=s=>{s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor(s%3600/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
export function render(onToggle,onDelete,onValue,onTimer,onEdit){const d=key(state.selectedDate);$("todayTitle").textContent=state.selectedDate.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"});$("selectedDayLabel").textContent=d===key(new Date())?"Сегодня":fmtDate(d);$("todayButton").hidden=d===key(new Date());
const list=$("dailyList");list.innerHTML="";for(const t of state.dailyTasks.filter(x=>x.active!==false)){const v=state.completions[t.id]?.[d]??(t.type==="timer"?0:"");const done=t.type==="timer"?Number(v)>=Number(t.target||3600):t.type==="value"?String(v).trim()!=="":!!v;const e=document.createElement("div");e.className="task"+(done?" completed":"");e.innerHTML=`<button class="checkbox">${done?"✓":""}</button><div class="task-icon">${t.icon||"🎮"}</div><div class="task-content"><div class="task-name">${esc(t.name)}</div><div class="task-meta">${esc(t.note|| (t.type==="timer"?"таймер 1 час":t.type==="value"?(v?"значение сохранено":"введите значение"):"каждый день"))}</div></div>`;e.querySelector(".checkbox").onclick=()=>onToggle(t);if(t.type==="value"){const w=document.createElement("div");w.className="value-editor";w.innerHTML=`<input class="value-input" placeholder="значение" value="${esc(v)}"><button class="value-save">OK</button>`;w.querySelector(".value-save").onclick=()=>onValue(t,w.querySelector("input").value.trim());w.querySelector("input").onkeydown=z=>z.key==="Enter"&&onValue(t,z.target.value.trim());e.appendChild(w)}if(t.type==="timer"){const w=document.createElement("div");w.className="timer";w.innerHTML=`<span class="timer-value">${fmtTime(v)}</span><button class="timer-button">${state.timers[t.id]?.date===d?"Стоп":"Старт"}</button><button class="timer-reset">↺</button>`;w.querySelector(".timer-button").onclick=()=>onTimer(t,"toggle");w.querySelector(".timer-reset").onclick=()=>onTimer(t,"reset");e.appendChild(w)}const a=document.createElement("div");a.className="task-actions";a.innerHTML='<button class="task-action edit-action">✎</button><button class="task-action">×</button>';a.children[0].onclick=()=>onEdit(t,"daily");a.children[1].onclick=()=>onDelete(t);e.appendChild(a);list.appendChild(e)}$("dailyCount").textContent=state.dailyTasks.length;
const pl=$("plannedList");pl.innerHTML="";const future=state.plannedTasks.filter(t=>t.date>=key(new Date())).sort((a,b)=>a.date.localeCompare(b.date));for(const t of future.slice(0,10)){const x=new Date(t.date+"T00:00:00"),e=document.createElement("div");e.className="task"+(t.completed?" completed":"");e.innerHTML=`<button class="checkbox">${t.completed?"✓":""}</button><div class="planned-date"><b>${x.getDate()}</b><small>${x.toLocaleDateString("ru-RU",{month:"short"})}</small></div><div class="task-icon">${t.icon||"🎯"}</div><div class="planned-content"><div class="planned-name">${esc(t.name)}</div><div class="planned-meta">${fmtDate(t.date)}${t.note?" · "+esc(t.note):""}</div></div>`;e.querySelector(".checkbox").onclick=()=>onToggle(t);const a=document.createElement("div");a.className="task-actions";a.innerHTML='<button class="task-action edit-action">✎</button><button class="task-action">×</button>';a.children[0].onclick=()=>onEdit(t,"planned");a.children[1].onclick=()=>onDelete(t);e.appendChild(a);pl.appendChild(e)}$("plannedCount").textContent=future.length;renderProgress();renderStats();renderSpecial()}
function renderProgress(){const d=key(state.selectedDate),a=state.dailyTasks.filter(x=>x.active!==false);let n=0;for(const t of a){const v=state.completions[t.id]?.[d];if(t.type==="timer"?Number(v)>=Number(t.target||3600):t.type==="value"?String(v??"").trim()!=="":!!v)n++}const p=a.length?Math.round(n/a.length*100):0;$("progressBar").style.width=p+"%";$("todayPercent").textContent=p+"%";$("progressText").textContent=`${n} из ${a.length} выполнено`}
function renderStats(){let n=0;for(const id in state.completions)for(const d in state.completions[id])if(state.completions[id][d])n++;$("statCompleted").textContent=n;$("statPercent").textContent="—";$("statStreak").textContent="—"}
function renderSpecial(){const d=key(state.selectedDate),c=$("todaySpecialList");c.innerHTML="";state.plannedTasks.filter(t=>t.date===d).forEach(t=>{const e=document.createElement("div");e.className="task"+(t.completed?" completed":"");e.innerHTML=`<button class="checkbox">${t.completed?"✓":""}</button><div class="task-icon">${t.icon||"🎯"}</div><div class="task-content"><div class="task-name">${esc(t.name)}</div><div class="task-meta">${fmtDate(d)}</div></div>`;e.querySelector(".checkbox").onclick=()=>window.__togglePlanned(t);const a=document.createElement("div");a.className="task-actions";a.innerHTML='<button class="task-action edit-action">✎</button><button class="task-action">×</button>';a.children[0].onclick=()=>window.__edit(t,"planned");a.children[1].onclick=()=>window.__deletePlanned(t);e.appendChild(a);c.appendChild(e)});$("todaySpecialSection").hidden=!c.children.length}
